'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class database_firewall_rules
    Public Property id As Integer
    Public Property name As String
    Public Property start_ip_address As String
    Public Property end_ip_address As String
    Public Property create_date As Date
    Public Property modify_date As Date

End Class
